var namespacescore =
[
    [ "commands", null, [
      [ "FactoryInserter", "structscore_1_1commands_1_1_factory_inserter.html", "structscore_1_1commands_1_1_factory_inserter" ]
    ] ],
    [ "detail", null, [
      [ "dereference_visitor", "structscore_1_1detail_1_1dereference__visitor.html", "structscore_1_1detail_1_1dereference__visitor" ]
    ] ],
    [ "gfx", "namespacescore_1_1gfx.html", "namespacescore_1_1gfx" ],
    [ "Modifier", null, [
      [ "Click_tag", "structscore_1_1_modifier_1_1_click__tag.html", null ],
      [ "Move_tag", "structscore_1_1_modifier_1_1_move__tag.html", null ],
      [ "Release_tag", "structscore_1_1_modifier_1_1_release__tag.html", null ]
    ] ],
    [ "PluginLoader", null, [
      [ "PluginDependencyGraph", "structscore_1_1_plugin_loader_1_1_plugin_dependency_graph.html", "structscore_1_1_plugin_loader_1_1_plugin_dependency_graph" ]
    ] ],
    [ "testing", null, [
      [ "MockApplication", "structscore_1_1testing_1_1_mock_application.html", "structscore_1_1testing_1_1_mock_application" ]
    ] ],
    [ "uuids", null, [
      [ "string_generator", "structscore_1_1uuids_1_1string__generator.html", "structscore_1_1uuids_1_1string__generator" ],
      [ "uuid", "structscore_1_1uuids_1_1uuid.html", "structscore_1_1uuids_1_1uuid" ]
    ] ],
    [ "AboutDialog", "classscore_1_1_about_dialog.html", "classscore_1_1_about_dialog" ],
    [ "Action", "classscore_1_1_action.html", "classscore_1_1_action" ],
    [ "ActionCondition", "structscore_1_1_action_condition.html", "structscore_1_1_action_condition" ],
    [ "ActionContainer", "structscore_1_1_action_container.html", "structscore_1_1_action_container" ],
    [ "ActionGroup", "classscore_1_1_action_group.html", "classscore_1_1_action_group" ],
    [ "ActionManager", "classscore_1_1_action_manager.html", "classscore_1_1_action_manager" ],
    [ "Addon", "structscore_1_1_addon.html", "structscore_1_1_addon" ],
    [ "AddRemoveList", "classscore_1_1_add_remove_list.html", "classscore_1_1_add_remove_list" ],
    [ "AggregateCommand", "classscore_1_1_aggregate_command.html", "classscore_1_1_aggregate_command" ],
    [ "any_serializer", "structscore_1_1any__serializer.html", "structscore_1_1any__serializer" ],
    [ "any_serializer_t", "structscore_1_1any__serializer__t.html", "structscore_1_1any__serializer__t" ],
    [ "ApplicationComponents", "classscore_1_1_application_components.html", "classscore_1_1_application_components" ],
    [ "ApplicationComponentsData", "structscore_1_1_application_components_data.html", "structscore_1_1_application_components_data" ],
    [ "ApplicationContext", "structscore_1_1_application_context.html", "structscore_1_1_application_context" ],
    [ "ApplicationInterface", "classscore_1_1_application_interface.html", "classscore_1_1_application_interface" ],
    [ "ApplicationPlugin", "classscore_1_1_application_plugin.html", "classscore_1_1_application_plugin" ],
    [ "ApplicationPlugin_QtInterface", "classscore_1_1_application_plugin___qt_interface.html", "classscore_1_1_application_plugin___qt_interface" ],
    [ "ApplicationRegistrar", "classscore_1_1_application_registrar.html", "classscore_1_1_application_registrar" ],
    [ "ApplicationServices", "structscore_1_1_application_services.html", "structscore_1_1_application_services" ],
    [ "ApplicationSettings", "structscore_1_1_application_settings.html", "structscore_1_1_application_settings" ],
    [ "ArrowButton", "classscore_1_1_arrow_button.html", "classscore_1_1_arrow_button" ],
    [ "ArrowDialog", "classscore_1_1_arrow_dialog.html", "classscore_1_1_arrow_dialog" ],
    [ "BackgroundItem", "classscore_1_1_background_item.html", "classscore_1_1_background_item" ],
    [ "BarSpinBox", "structscore_1_1_bar_spin_box.html", "structscore_1_1_bar_spin_box" ],
    [ "BottomToolbarWidget", "classscore_1_1_bottom_toolbar_widget.html", "classscore_1_1_bottom_toolbar_widget" ],
    [ "Brush", "structscore_1_1_brush.html", "structscore_1_1_brush" ],
    [ "BrushSet", "structscore_1_1_brush_set.html", "structscore_1_1_brush_set" ],
    [ "ColorBang", "classscore_1_1_color_bang.html", "classscore_1_1_color_bang" ],
    [ "ColorRef", "structscore_1_1_color_ref.html", "structscore_1_1_color_ref" ],
    [ "ComboBox", "classscore_1_1_combo_box.html", "classscore_1_1_combo_box" ],
    [ "ComboSlider", "structscore_1_1_combo_slider.html", "structscore_1_1_combo_slider" ],
    [ "Command", "classscore_1_1_command.html", "classscore_1_1_command" ],
    [ "CommandBackupFile", "classscore_1_1_command_backup_file.html", "classscore_1_1_command_backup_file" ],
    [ "CommandData", "structscore_1_1_command_data.html", "structscore_1_1_command_data" ],
    [ "CommandFactory_QtInterface", "classscore_1_1_command_factory___qt_interface.html", "classscore_1_1_command_factory___qt_interface" ],
    [ "CommandKeyHash", "structscore_1_1_command_key_hash.html", "structscore_1_1_command_key_hash" ],
    [ "CommandSpinbox", "structscore_1_1_command_spinbox.html", "structscore_1_1_command_spinbox" ],
    [ "CommandStack", "classscore_1_1_command_stack.html", "classscore_1_1_command_stack" ],
    [ "CommandStackBackup", "structscore_1_1_command_stack_backup.html", "structscore_1_1_command_stack_backup" ],
    [ "CommandStackFacade", "classscore_1_1_command_stack_facade.html", "classscore_1_1_command_stack_facade" ],
    [ "CommandStore", "structscore_1_1_command_store.html", null ],
    [ "Component", "classscore_1_1_component.html", "classscore_1_1_component" ],
    [ "ComponentHierarchyManager", "classscore_1_1_component_hierarchy_manager.html", "classscore_1_1_component_hierarchy_manager" ],
    [ "Components", "structscore_1_1_components.html", "structscore_1_1_components" ],
    [ "CoreApplicationPlugin", "classscore_1_1_core_application_plugin.html", "classscore_1_1_core_application_plugin" ],
    [ "CustomActionCondition", "structscore_1_1_custom_action_condition.html", "structscore_1_1_custom_action_condition" ],
    [ "DefaultComboImpl", "structscore_1_1_default_combo_impl.html", null ],
    [ "DefaultedGenericComponentFactoryList", "classscore_1_1_defaulted_generic_component_factory_list.html", "classscore_1_1_defaulted_generic_component_factory_list" ],
    [ "DefaultGraphicsKnobImpl", "structscore_1_1_default_graphics_knob_impl.html", null ],
    [ "DefaultGraphicsSliderImpl", "structscore_1_1_default_graphics_slider_impl.html", null ],
    [ "delete_later", "structscore_1_1delete__later.html", "structscore_1_1delete__later" ],
    [ "Dispatcher", "structscore_1_1_dispatcher.html", "structscore_1_1_dispatcher" ],
    [ "Dispatcher_T", "structscore_1_1_dispatcher___t.html", "structscore_1_1_dispatcher___t" ],
    [ "Document", "classscore_1_1_document.html", "classscore_1_1_document" ],
    [ "DocumentActionCondition", "structscore_1_1_document_action_condition.html", "structscore_1_1_document_action_condition" ],
    [ "DocumentBackupManager", "classscore_1_1_document_backup_manager.html", "classscore_1_1_document_backup_manager" ],
    [ "DocumentBackups", "structscore_1_1_document_backups.html", null ],
    [ "DocumentBuilder", "classscore_1_1_document_builder.html", "classscore_1_1_document_builder" ],
    [ "DocumentContext", "structscore_1_1_document_context.html", "structscore_1_1_document_context" ],
    [ "DocumentDelegateFactory", "classscore_1_1_document_delegate_factory.html", "classscore_1_1_document_delegate_factory" ],
    [ "DocumentDelegateList", "classscore_1_1_document_delegate_list.html", "classscore_1_1_document_delegate_list" ],
    [ "DocumentDelegateModel", "classscore_1_1_document_delegate_model.html", "classscore_1_1_document_delegate_model" ],
    [ "DocumentDelegatePresenter", "classscore_1_1_document_delegate_presenter.html", "classscore_1_1_document_delegate_presenter" ],
    [ "DocumentDelegateView", "classscore_1_1_document_delegate_view.html", "classscore_1_1_document_delegate_view" ],
    [ "DocumentList", "structscore_1_1_document_list.html", "structscore_1_1_document_list" ],
    [ "DocumentManager", "classscore_1_1_document_manager.html", "classscore_1_1_document_manager" ],
    [ "DocumentMetadata", "structscore_1_1_document_metadata.html", "structscore_1_1_document_metadata" ],
    [ "DocumentModel", "classscore_1_1_document_model.html", "classscore_1_1_document_model" ],
    [ "DocumentPlugin", "classscore_1_1_document_plugin.html", "classscore_1_1_document_plugin" ],
    [ "DocumentPluginFactory", "classscore_1_1_document_plugin_factory.html", "classscore_1_1_document_plugin_factory" ],
    [ "DocumentPluginFactory_T", "classscore_1_1_document_plugin_factory___t.html", "classscore_1_1_document_plugin_factory___t" ],
    [ "DocumentPluginFactoryList", "classscore_1_1_document_plugin_factory_list.html", "classscore_1_1_document_plugin_factory_list" ],
    [ "DocumentPresenter", "classscore_1_1_document_presenter.html", "classscore_1_1_document_presenter" ],
    [ "DocumentValidator", "classscore_1_1_document_validator.html", "classscore_1_1_document_validator" ],
    [ "DocumentView", "classscore_1_1_document_view.html", "classscore_1_1_document_view" ],
    [ "DoubleSlider", "classscore_1_1_double_slider.html", "classscore_1_1_double_slider" ],
    [ "DoubleSpinboxWithEnter", "structscore_1_1_double_spinbox_with_enter.html", null ],
    [ "DragOverToolButton", "structscore_1_1_drag_over_tool_button.html", "structscore_1_1_drag_over_tool_button" ],
    [ "dynarray_impl", "classscore_1_1dynarray__impl.html", "classscore_1_1dynarray__impl" ],
    [ "dynvector_impl", "classscore_1_1dynvector__impl.html", "classscore_1_1dynvector__impl" ],
    [ "EmptyItem", "classscore_1_1_empty_item.html", "classscore_1_1_empty_item" ],
    [ "EmptyRectItem", "classscore_1_1_empty_rect_item.html", "classscore_1_1_empty_rect_item" ],
    [ "EnableActionIfDocument", "structscore_1_1_enable_action_if_document.html", "structscore_1_1_enable_action_if_document" ],
    [ "EnableWhenDocumentIs", "classscore_1_1_enable_when_document_is.html", null ],
    [ "EnableWhenFocusedObjectIs", "classscore_1_1_enable_when_focused_object_is.html", null ],
    [ "EnableWhenSelectionContains", "classscore_1_1_enable_when_selection_contains.html", null ],
    [ "Entity", "classscore_1_1_entity.html", "classscore_1_1_entity" ],
    [ "EntityList", "classscore_1_1_entity_list.html", "classscore_1_1_entity_list" ],
    [ "EntityMap", "classscore_1_1_entity_map.html", "classscore_1_1_entity_map" ],
    [ "EntityMapInserter", "classscore_1_1_entity_map_inserter.html", "classscore_1_1_entity_map_inserter" ],
    [ "EntityMapInserter< score::Entity< T > >", "classscore_1_1_entity_map_inserter_3_01score_1_1_entity_3_01_t_01_4_01_4.html", null ],
    [ "EventVisitor", "structscore_1_1_event_visitor.html", "structscore_1_1_event_visitor" ],
    [ "FactoryInterface_QtInterface", "classscore_1_1_factory_interface___qt_interface.html", "classscore_1_1_factory_interface___qt_interface" ],
    [ "FactoryList_QtInterface", "classscore_1_1_factory_list___qt_interface.html", "classscore_1_1_factory_list___qt_interface" ],
    [ "FileDownloader", "classscore_1_1_file_downloader.html", "classscore_1_1_file_downloader" ],
    [ "FileWatch", "classscore_1_1_file_watch.html", "classscore_1_1_file_watch" ],
    [ "FixedTabWidget", "classscore_1_1_fixed_tab_widget.html", "classscore_1_1_fixed_tab_widget" ],
    [ "FlicksSpinBox", "structscore_1_1_flicks_spin_box.html", "structscore_1_1_flicks_spin_box" ],
    [ "FocusActionCondition", "structscore_1_1_focus_action_condition.html", "structscore_1_1_focus_action_condition" ],
    [ "FocusFacade", "structscore_1_1_focus_facade.html", "structscore_1_1_focus_facade" ],
    [ "FocusManager", "structscore_1_1_focus_manager.html", "structscore_1_1_focus_manager" ],
    [ "FormLayout", "classscore_1_1_form_layout.html", "classscore_1_1_form_layout" ],
    [ "FormWidget", "classscore_1_1_form_widget.html", "classscore_1_1_form_widget" ],
    [ "GenericComponent", "classscore_1_1_generic_component.html", "classscore_1_1_generic_component" ],
    [ "GenericComponentFactory", "classscore_1_1_generic_component_factory.html", "classscore_1_1_generic_component_factory" ],
    [ "GenericComponentFactoryImpl", "classscore_1_1_generic_component_factory_impl.html", null ],
    [ "GenericComponentFactoryList", "classscore_1_1_generic_component_factory_list.html", "classscore_1_1_generic_component_factory_list" ],
    [ "GLCapabilities", "structscore_1_1_g_l_capabilities.html", "structscore_1_1_g_l_capabilities" ],
    [ "GraphicsDefaultLayout", "classscore_1_1_graphics_default_layout.html", "classscore_1_1_graphics_default_layout" ],
    [ "GraphicsGridColumnsLayout", "classscore_1_1_graphics_grid_columns_layout.html", "classscore_1_1_graphics_grid_columns_layout" ],
    [ "GraphicsGridRowsLayout", "classscore_1_1_graphics_grid_rows_layout.html", "classscore_1_1_graphics_grid_rows_layout" ],
    [ "GraphicsHBoxLayout", "classscore_1_1_graphics_h_box_layout.html", "classscore_1_1_graphics_h_box_layout" ],
    [ "GraphicsLayout", "classscore_1_1_graphics_layout.html", "classscore_1_1_graphics_layout" ],
    [ "GraphicsSplitLayout", "classscore_1_1_graphics_split_layout.html", "classscore_1_1_graphics_split_layout" ],
    [ "GraphicsTabLayout", "classscore_1_1_graphics_tab_layout.html", "classscore_1_1_graphics_tab_layout" ],
    [ "GraphicsVBoxLayout", "classscore_1_1_graphics_v_box_layout.html", "classscore_1_1_graphics_v_box_layout" ],
    [ "GUIApplicationContext", "structscore_1_1_g_u_i_application_context.html", "structscore_1_1_g_u_i_application_context" ],
    [ "GUIApplicationInterface", "classscore_1_1_g_u_i_application_interface.html", "classscore_1_1_g_u_i_application_interface" ],
    [ "GUIApplicationPlugin", "classscore_1_1_g_u_i_application_plugin.html", "classscore_1_1_g_u_i_application_plugin" ],
    [ "GUIApplicationRegistrar", "classscore_1_1_g_u_i_application_registrar.html", "classscore_1_1_g_u_i_application_registrar" ],
    [ "GUIElements", "structscore_1_1_g_u_i_elements.html", "structscore_1_1_g_u_i_elements" ],
    [ "HelperPanelDelegate", "classscore_1_1_helper_panel_delegate.html", "classscore_1_1_helper_panel_delegate" ],
    [ "HierarchicalMember", "structscore_1_1_hierarchical_member.html", "structscore_1_1_hierarchical_member" ],
    [ "HierarchicModel", "structscore_1_1_hierarchic_model.html", null ],
    [ "HierarchicModel< Model, Arg >", "structscore_1_1_hierarchic_model_3_01_model_00_01_arg_01_4.html", "structscore_1_1_hierarchic_model_3_01_model_00_01_arg_01_4" ],
    [ "HierarchicModel< Model, Arg, Args... >", "structscore_1_1_hierarchic_model_3_01_model_00_01_arg_00_01_args_8_8_8_01_4.html", "structscore_1_1_hierarchic_model_3_01_model_00_01_arg_00_01_args_8_8_8_01_4" ],
    [ "HSeparator", "classscore_1_1_h_separator.html", "classscore_1_1_h_separator" ],
    [ "HTTPGet", "classscore_1_1_h_t_t_p_get.html", "classscore_1_1_h_t_t_p_get" ],
    [ "IconProvider", "classscore_1_1_icon_provider.html", "classscore_1_1_icon_provider" ],
    [ "IdGen", "structscore_1_1_id_gen.html", "structscore_1_1_id_gen" ],
    [ "indirect_iterator", "structscore_1_1indirect__iterator.html", "structscore_1_1indirect__iterator" ],
    [ "indirect_map_iterator", "structscore_1_1indirect__map__iterator.html", "structscore_1_1indirect__map__iterator" ],
    [ "indirect_ptr_iterator", "structscore_1_1indirect__ptr__iterator.html", "structscore_1_1indirect__ptr__iterator" ],
    [ "IndirectArray", "classscore_1_1_indirect_array.html", "classscore_1_1_indirect_array" ],
    [ "IndirectContainer", "classscore_1_1_indirect_container.html", "classscore_1_1_indirect_container" ],
    [ "IndirectContainerWrapper", "classscore_1_1_indirect_container_wrapper.html", "classscore_1_1_indirect_container_wrapper" ],
    [ "IndirectMap", "classscore_1_1_indirect_map.html", "classscore_1_1_indirect_map" ],
    [ "IndirectUnorderedMap", "classscore_1_1_indirect_unordered_map.html", "classscore_1_1_indirect_unordered_map" ],
    [ "InfiniteScroller", "structscore_1_1_infinite_scroller.html", null ],
    [ "InteractiveLabel", "classscore_1_1_interactive_label.html", "classscore_1_1_interactive_label" ],
    [ "InterfaceBase", "classscore_1_1_interface_base.html", "classscore_1_1_interface_base" ],
    [ "InterfaceList", "classscore_1_1_interface_list.html", "classscore_1_1_interface_list" ],
    [ "InterfaceListBase", "classscore_1_1_interface_list_base.html", "classscore_1_1_interface_list_base" ],
    [ "IntSlider", "classscore_1_1_int_slider.html", "classscore_1_1_int_slider" ],
    [ "ItemBounder", "classscore_1_1_item_bounder.html", "classscore_1_1_item_bounder" ],
    [ "lazy_init_t", "structscore_1_1lazy__init__t.html", null ],
    [ "linear_id_generator", "structscore_1_1linear__id__generator.html", null ],
    [ "LoadedPluginVersions", "structscore_1_1_loaded_plugin_versions.html", "structscore_1_1_loaded_plugin_versions" ],
    [ "LockHelper", "classscore_1_1_lock_helper.html", "classscore_1_1_lock_helper" ],
    [ "LogMessage", "structscore_1_1_log_message.html", "structscore_1_1_log_message" ],
    [ "LogMessagesItemModel", "classscore_1_1_log_messages_item_model.html", "classscore_1_1_log_messages_item_model" ],
    [ "MarginLess", "classscore_1_1_margin_less.html", "classscore_1_1_margin_less" ],
    [ "MatchedTransition", "classscore_1_1_matched_transition.html", "classscore_1_1_matched_transition" ],
    [ "MatchingFactory", "classscore_1_1_matching_factory.html", "classscore_1_1_matching_factory" ],
    [ "MaxRangeSpinBox", "classscore_1_1_max_range_spin_box.html", "classscore_1_1_max_range_spin_box" ],
    [ "Menu", "classscore_1_1_menu.html", "classscore_1_1_menu" ],
    [ "MenuManager", "classscore_1_1_menu_manager.html", "classscore_1_1_menu_manager" ],
    [ "Menus", "structscore_1_1_menus.html", null ],
    [ "MessagesPanelDelegate", "classscore_1_1_messages_panel_delegate.html", "classscore_1_1_messages_panel_delegate" ],
    [ "MessagesPanelDelegateFactory", "classscore_1_1_messages_panel_delegate_factory.html", null ],
    [ "MetaAction", "structscore_1_1_meta_action.html", null ],
    [ "MinimalApplication", "classscore_1_1_minimal_application.html", "classscore_1_1_minimal_application" ],
    [ "MinimalGUIApplication", "classscore_1_1_minimal_g_u_i_application.html", "classscore_1_1_minimal_g_u_i_application" ],
    [ "MissingCommandException", "classscore_1_1_missing_command_exception.html", "classscore_1_1_missing_command_exception" ],
    [ "ModelMetadata", "classscore_1_1_model_metadata.html", "classscore_1_1_model_metadata" ],
    [ "NumberedEvent", "structscore_1_1_numbered_event.html", "structscore_1_1_numbered_event" ],
    [ "NumberedWithPath_Event", "structscore_1_1_numbered_with_path___event.html", "structscore_1_1_numbered_with_path___event" ],
    [ "ObjectEditor", "structscore_1_1_object_editor.html", "structscore_1_1_object_editor" ],
    [ "ObjectEditorList", "classscore_1_1_object_editor_list.html", "classscore_1_1_object_editor_list" ],
    [ "ObjectLocker", "classscore_1_1_object_locker.html", "classscore_1_1_object_locker" ],
    [ "OpenDocumentsFile", "structscore_1_1_open_documents_file.html", null ],
    [ "PaintVisitor", "structscore_1_1_paint_visitor.html", "structscore_1_1_paint_visitor" ],
    [ "PanelDelegate", "classscore_1_1_panel_delegate.html", "classscore_1_1_panel_delegate" ],
    [ "PanelDelegateFactory", "classscore_1_1_panel_delegate_factory.html", "classscore_1_1_panel_delegate_factory" ],
    [ "PanelDelegateFactoryList", "classscore_1_1_panel_delegate_factory_list.html", "classscore_1_1_panel_delegate_factory_list" ],
    [ "PanelStatus", "structscore_1_1_panel_status.html", "structscore_1_1_panel_status" ],
    [ "PathInfo", "structscore_1_1_path_info.html", "structscore_1_1_path_info" ],
    [ "Plugin", "structscore_1_1_plugin.html", null ],
    [ "Plugin_QtInterface", "classscore_1_1_plugin___qt_interface.html", "classscore_1_1_plugin___qt_interface" ],
    [ "PluginWindow", "classscore_1_1_plugin_window.html", "classscore_1_1_plugin_window" ],
    [ "PolymorphicComponentHierarchyManager", "classscore_1_1_polymorphic_component_hierarchy_manager.html", "classscore_1_1_polymorphic_component_hierarchy_manager" ],
    [ "PositionedEvent", "structscore_1_1_positioned_event.html", "structscore_1_1_positioned_event" ],
    [ "PositionedEvent< Scenario::Point >", "structscore_1_1_positioned_event_3_01_scenario_1_1_point_01_4.html", "structscore_1_1_positioned_event_3_01_scenario_1_1_point_01_4" ],
    [ "Presenter", "classscore_1_1_presenter.html", "classscore_1_1_presenter" ],
    [ "ProjectSettings", "classscore_1_1_project_settings.html", "classscore_1_1_project_settings" ],
    [ "ProjectSettingsDelegateFactory_T", "classscore_1_1_project_settings_delegate_factory___t.html", null ],
    [ "ProjectSettingsFactory", "classscore_1_1_project_settings_factory.html", "classscore_1_1_project_settings_factory" ],
    [ "ProjectSettingsModel", "classscore_1_1_project_settings_model.html", "classscore_1_1_project_settings_model" ],
    [ "PropertyCommand", "classscore_1_1_property_command.html", "classscore_1_1_property_command" ],
    [ "PropertyCommand_T", "classscore_1_1_property_command___t.html", "classscore_1_1_property_command___t" ],
    [ "QGraphicsButton", "classscore_1_1_q_graphics_button.html", "classscore_1_1_q_graphics_button" ],
    [ "QGraphicsCheckBox", "classscore_1_1_q_graphics_check_box.html", "classscore_1_1_q_graphics_check_box" ],
    [ "QGraphicsCombo", "classscore_1_1_q_graphics_combo.html", "classscore_1_1_q_graphics_combo" ],
    [ "QGraphicsDraggablePixmap", "classscore_1_1_q_graphics_draggable_pixmap.html", "classscore_1_1_q_graphics_draggable_pixmap" ],
    [ "QGraphicsEnum", "classscore_1_1_q_graphics_enum.html", "classscore_1_1_q_graphics_enum" ],
    [ "QGraphicsHSVChooser", "classscore_1_1_q_graphics_h_s_v_chooser.html", "classscore_1_1_q_graphics_h_s_v_chooser" ],
    [ "QGraphicsIntSlider", "classscore_1_1_q_graphics_int_slider.html", "classscore_1_1_q_graphics_int_slider" ],
    [ "QGraphicsKnob", "classscore_1_1_q_graphics_knob.html", "classscore_1_1_q_graphics_knob" ],
    [ "QGraphicsLogKnob", "classscore_1_1_q_graphics_log_knob.html", "classscore_1_1_q_graphics_log_knob" ],
    [ "QGraphicsLogSlider", "classscore_1_1_q_graphics_log_slider.html", "classscore_1_1_q_graphics_log_slider" ],
    [ "QGraphicsMultiSlider", "classscore_1_1_q_graphics_multi_slider.html", "classscore_1_1_q_graphics_multi_slider" ],
    [ "QGraphicsNoteChooser", "classscore_1_1_q_graphics_note_chooser.html", "classscore_1_1_q_graphics_note_chooser" ],
    [ "QGraphicsPixmapButton", "classscore_1_1_q_graphics_pixmap_button.html", "classscore_1_1_q_graphics_pixmap_button" ],
    [ "QGraphicsPixmapEnum", "classscore_1_1_q_graphics_pixmap_enum.html", "classscore_1_1_q_graphics_pixmap_enum" ],
    [ "QGraphicsPixmapToggle", "classscore_1_1_q_graphics_pixmap_toggle.html", "classscore_1_1_q_graphics_pixmap_toggle" ],
    [ "QGraphicsRangeSlider", "classscore_1_1_q_graphics_range_slider.html", "classscore_1_1_q_graphics_range_slider" ],
    [ "QGraphicsSelectablePixmapToggle", "classscore_1_1_q_graphics_selectable_pixmap_toggle.html", "classscore_1_1_q_graphics_selectable_pixmap_toggle" ],
    [ "QGraphicsSlider", "classscore_1_1_q_graphics_slider.html", "classscore_1_1_q_graphics_slider" ],
    [ "QGraphicsSliderBase", "structscore_1_1_q_graphics_slider_base.html", "structscore_1_1_q_graphics_slider_base" ],
    [ "QGraphicsSpinbox", "classscore_1_1_q_graphics_spinbox.html", "classscore_1_1_q_graphics_spinbox" ],
    [ "QGraphicsTextButton", "classscore_1_1_q_graphics_text_button.html", "classscore_1_1_q_graphics_text_button" ],
    [ "QGraphicsTimeChooser", "classscore_1_1_q_graphics_time_chooser.html", "classscore_1_1_q_graphics_time_chooser" ],
    [ "QGraphicsToggle", "classscore_1_1_q_graphics_toggle.html", "classscore_1_1_q_graphics_toggle" ],
    [ "QGraphicsXYChooser", "classscore_1_1_q_graphics_x_y_chooser.html", "classscore_1_1_q_graphics_x_y_chooser" ],
    [ "QGraphicsXYZChooser", "classscore_1_1_q_graphics_x_y_z_chooser.html", "classscore_1_1_q_graphics_x_y_z_chooser" ],
    [ "QGraphicsXYZSpinboxChooser", "classscore_1_1_q_graphics_x_y_z_spinbox_chooser.html", "classscore_1_1_q_graphics_x_y_z_spinbox_chooser" ],
    [ "QuantificationWidget", "classscore_1_1_quantification_widget.html", "classscore_1_1_quantification_widget" ],
    [ "random_id_generator", "structscore_1_1random__id__generator.html", null ],
    [ "ReactiveLabel", "classscore_1_1_reactive_label.html", "classscore_1_1_reactive_label" ],
    [ "RectItem", "classscore_1_1_rect_item.html", "classscore_1_1_rect_item" ],
    [ "RectSplitter", "classscore_1_1_rect_splitter.html", "classscore_1_1_rect_splitter" ],
    [ "RectWidget", "classscore_1_1_rect_widget.html", "classscore_1_1_rect_widget" ],
    [ "RecursiveWatch", "classscore_1_1_recursive_watch.html", "classscore_1_1_recursive_watch" ],
    [ "ResizeableItem", "classscore_1_1_resizeable_item.html", "classscore_1_1_resizeable_item" ],
    [ "RestorableDocument", "structscore_1_1_restorable_document.html", "structscore_1_1_restorable_document" ],
    [ "RightClickImpl", "structscore_1_1_right_click_impl.html", "structscore_1_1_right_click_impl" ],
    [ "SearchLineEdit", "classscore_1_1_search_line_edit.html", "classscore_1_1_search_line_edit" ],
    [ "SecondSpinBox", "structscore_1_1_second_spin_box.html", "structscore_1_1_second_spin_box" ],
    [ "SelectionActionCondition", "structscore_1_1_selection_action_condition.html", "structscore_1_1_selection_action_condition" ],
    [ "SelectionDispatcher", "classscore_1_1_selection_dispatcher.html", "classscore_1_1_selection_dispatcher" ],
    [ "SelectionStack", "classscore_1_1_selection_stack.html", "classscore_1_1_selection_stack" ],
    [ "SerializableDocumentPlugin", "classscore_1_1_serializable_document_plugin.html", "classscore_1_1_serializable_document_plugin" ],
    [ "SerializableInterface", "classscore_1_1_serializable_interface.html", "classscore_1_1_serializable_interface" ],
    [ "Settings", "classscore_1_1_settings.html", "classscore_1_1_settings" ],
    [ "SettingsCommand", "classscore_1_1_settings_command.html", "classscore_1_1_settings_command" ],
    [ "SettingsCommandBase", "classscore_1_1_settings_command_base.html", "classscore_1_1_settings_command_base" ],
    [ "SettingsCommandDispatcher", "classscore_1_1_settings_command_dispatcher.html", "classscore_1_1_settings_command_dispatcher" ],
    [ "SettingsDelegateFactory", "classscore_1_1_settings_delegate_factory.html", "classscore_1_1_settings_delegate_factory" ],
    [ "SettingsDelegateFactory_T", "classscore_1_1_settings_delegate_factory___t.html", null ],
    [ "SettingsDelegateModel", "classscore_1_1_settings_delegate_model.html", "classscore_1_1_settings_delegate_model" ],
    [ "SettingsDelegatePresenter", "classscore_1_1_settings_delegate_presenter.html", "classscore_1_1_settings_delegate_presenter" ],
    [ "SettingsDelegateView", "classscore_1_1_settings_delegate_view.html", "classscore_1_1_settings_delegate_view" ],
    [ "SettingsParameterMetadata", "structscore_1_1_settings_parameter_metadata.html", "structscore_1_1_settings_parameter_metadata" ],
    [ "SettingsPresenter", "classscore_1_1_settings_presenter.html", "classscore_1_1_settings_presenter" ],
    [ "SettingsView", "classscore_1_1_settings_view.html", "classscore_1_1_settings_view" ],
    [ "SimpleTextItem", "classscore_1_1_simple_text_item.html", "classscore_1_1_simple_text_item" ],
    [ "SizeVisitor", "structscore_1_1_size_visitor.html", "structscore_1_1_size_visitor" ],
    [ "Skin", "classscore_1_1_skin.html", "classscore_1_1_skin" ],
    [ "SliderWrapper", "structscore_1_1_slider_wrapper.html", "structscore_1_1_slider_wrapper" ],
    [ "SpeedSlider", "structscore_1_1_speed_slider.html", "structscore_1_1_speed_slider" ],
    [ "SpinBox", "classscore_1_1_spin_box.html", null ],
    [ "SpinBox< double >", "classscore_1_1_spin_box_3_01double_01_4.html", "classscore_1_1_spin_box_3_01double_01_4" ],
    [ "SpinBox< float >", "classscore_1_1_spin_box_3_01float_01_4.html", "classscore_1_1_spin_box_3_01float_01_4" ],
    [ "StartScreen", "classscore_1_1_start_screen.html", "classscore_1_1_start_screen" ],
    [ "StartScreenLink", "structscore_1_1_start_screen_link.html", "structscore_1_1_start_screen_link" ],
    [ "StateAwareTransition", "classscore_1_1_state_aware_transition.html", "classscore_1_1_state_aware_transition" ],
    [ "StaticPropertyCommand", "structscore_1_1_static_property_command.html", null ],
    [ "StaticPropertyCommand< AvndJit::Model::p_script >", "structscore_1_1_static_property_command_3_01_avnd_jit_1_1_model_1_1p__script_01_4.html", null ],
    [ "StaticPropertyCommand< Faust::FaustEffectModel::p_text >", "structscore_1_1_static_property_command_3_01_faust_1_1_faust_effect_model_1_1p__text_01_4.html", null ],
    [ "StaticPropertyCommand< Gfx::Filter::Model::p_program >", "structscore_1_1_static_property_command_3_01_gfx_1_1_filter_1_1_model_1_1p__program_01_4.html", null ],
    [ "StaticPropertyCommand< Jit::BytebeatModel::p_script >", "structscore_1_1_static_property_command_3_01_jit_1_1_bytebeat_model_1_1p__script_01_4.html", null ],
    [ "StaticPropertyCommand< Jit::JitEffectModel::p_script >", "structscore_1_1_static_property_command_3_01_jit_1_1_jit_effect_model_1_1p__script_01_4.html", null ],
    [ "StaticPropertyCommand< JS::ProcessModel::p_script >", "structscore_1_1_static_property_command_3_01_j_s_1_1_process_model_1_1p__script_01_4.html", null ],
    [ "StringConstants", "structscore_1_1_string_constants.html", "structscore_1_1_string_constants" ],
    [ "SubtypeVariant", "classscore_1_1_subtype_variant.html", "classscore_1_1_subtype_variant" ],
    [ "TaskPool", "classscore_1_1_task_pool.html", "classscore_1_1_task_pool" ],
    [ "TemplatedSpinBox", "structscore_1_1_templated_spin_box.html", null ],
    [ "TemplatedSpinBox< double >", "structscore_1_1_templated_spin_box_3_01double_01_4.html", "structscore_1_1_templated_spin_box_3_01double_01_4" ],
    [ "TemplatedSpinBox< float >", "structscore_1_1_templated_spin_box_3_01float_01_4.html", "structscore_1_1_templated_spin_box_3_01float_01_4" ],
    [ "TemplatedSpinBox< int >", "structscore_1_1_templated_spin_box_3_01int_01_4.html", "structscore_1_1_templated_spin_box_3_01int_01_4" ],
    [ "TextItem", "classscore_1_1_text_item.html", "classscore_1_1_text_item" ],
    [ "ThreadPool", "classscore_1_1_thread_pool.html", "classscore_1_1_thread_pool" ],
    [ "TimeSignatureWidget", "classscore_1_1_time_signature_widget.html", "classscore_1_1_time_signature_widget" ],
    [ "TimeSpinBox", "classscore_1_1_time_spin_box.html", "classscore_1_1_time_spin_box" ],
    [ "TitleBar", "classscore_1_1_title_bar.html", "classscore_1_1_title_bar" ],
    [ "ToggleButton", "structscore_1_1_toggle_button.html", "structscore_1_1_toggle_button" ],
    [ "Toolbar", "classscore_1_1_toolbar.html", "classscore_1_1_toolbar" ],
    [ "ToolbarManager", "classscore_1_1_toolbar_manager.html", "classscore_1_1_toolbar_manager" ],
    [ "TreeViewExpandState", "structscore_1_1_tree_view_expand_state.html", "structscore_1_1_tree_view_expand_state" ],
    [ "UndoApplicationPlugin", "classscore_1_1_undo_application_plugin.html", "classscore_1_1_undo_application_plugin" ],
    [ "UndoListWidget", "classscore_1_1_undo_list_widget.html", "classscore_1_1_undo_list_widget" ],
    [ "UndoPanelDelegate", "classscore_1_1_undo_panel_delegate.html", "classscore_1_1_undo_panel_delegate" ],
    [ "UndoPanelDelegateFactory", "classscore_1_1_undo_panel_delegate_factory.html", null ],
    [ "ValidityChecker", "classscore_1_1_validity_checker.html", "classscore_1_1_validity_checker" ],
    [ "ValidityCheckerList", "classscore_1_1_validity_checker_list.html", "classscore_1_1_validity_checker_list" ],
    [ "ValueAssigner", "structscore_1_1_value_assigner.html", null ],
    [ "ValueAssigner< float >", "structscore_1_1_value_assigner_3_01float_01_4.html", "structscore_1_1_value_assigner_3_01float_01_4" ],
    [ "ValueAssigner< int >", "structscore_1_1_value_assigner_3_01int_01_4.html", "structscore_1_1_value_assigner_3_01int_01_4" ],
    [ "ValueAssigner< ossia::value >", "structscore_1_1_value_assigner_3_01ossia_1_1value_01_4.html", "structscore_1_1_value_assigner_3_01ossia_1_1value_01_4" ],
    [ "ValueDoubleSlider", "structscore_1_1_value_double_slider.html", "structscore_1_1_value_double_slider" ],
    [ "ValueLogDoubleSlider", "structscore_1_1_value_log_double_slider.html", "structscore_1_1_value_log_double_slider" ],
    [ "ValueSlider", "structscore_1_1_value_slider.html", "structscore_1_1_value_slider" ],
    [ "VariantBasedNode", "classscore_1_1_variant_based_node.html", "classscore_1_1_variant_based_node" ],
    [ "Version", "classscore_1_1_version.html", "classscore_1_1_version" ],
    [ "View", "classscore_1_1_view.html", "classscore_1_1_view" ],
    [ "VisibilityNotifying", "classscore_1_1_visibility_notifying.html", "classscore_1_1_visibility_notifying" ],
    [ "VolumeSlider", "structscore_1_1_volume_slider.html", "structscore_1_1_volume_slider" ],
    [ "VSeparator", "classscore_1_1_v_separator.html", "classscore_1_1_v_separator" ],
    [ "ZoomItem", "classscore_1_1_zoom_item.html", "classscore_1_1_zoom_item" ]
];