var namespaceoscr =
[
    [ "con_unvalidated", "structoscr_1_1con__unvalidated.html", null ],
    [ "con_unvalidated_dynamic_port", "structoscr_1_1con__unvalidated__dynamic__port.html", null ],
    [ "CustomControl", "classoscr_1_1_custom_control.html", null ],
    [ "CustomControlFactory", "structoscr_1_1_custom_control_factory.html", null ],
    [ "CustomControlFactory< Node, avnd::field_reflection< N, Field > >", "structoscr_1_1_custom_control_factory_3_01_node_00_01avnd_1_1field__reflection_3_01_n_00_01_field_01_4_01_4.html", null ],
    [ "CustomFloatControl", "structoscr_1_1_custom_float_control.html", null ],
    [ "CustomFloatControlBase", "structoscr_1_1_custom_float_control_base.html", null ],
    [ "CustomItem", "classoscr_1_1_custom_item.html", "classoscr_1_1_custom_item" ],
    [ "CustomNodeProcess", "classoscr_1_1_custom_node_process.html", null ],
    [ "CustomTextGraphicsKnob", "classoscr_1_1_custom_text_graphics_knob.html", null ],
    [ "CustomTextGraphicsSlider", "classoscr_1_1_custom_text_graphics_slider.html", null ],
    [ "Deserializer", "structoscr_1_1_deserializer.html", null ],
    [ "DeviceImplementation", "classoscr_1_1_device_implementation.html", null ],
    [ "dispatch_control_setup", "structoscr_1_1dispatch__control__setup.html", null ],
    [ "EdgeItem", "structoscr_1_1_edge_item.html", null ],
    [ "Executor", "classoscr_1_1_executor.html", null ],
    [ "ExecutorFactory", "structoscr_1_1_executor_factory.html", null ],
    [ "GraphWidget", "structoscr_1_1_graph_widget.html", null ],
    [ "InletInitFunc", "structoscr_1_1_inlet_init_func.html", null ],
    [ "LayerFactory", "classoscr_1_1_layer_factory.html", null ],
    [ "LayoutBuilder", "structoscr_1_1_layout_builder.html", null ],
    [ "Logger", "structoscr_1_1_logger.html", null ],
    [ "MatchingWidget", "structoscr_1_1_matching_widget.html", null ],
    [ "MatchingWidget< Field >", "structoscr_1_1_matching_widget_3_01_field_01_4.html", null ],
    [ "MessageBusReader", "structoscr_1_1_message_bus_reader.html", null ],
    [ "MessageBusSender", "structoscr_1_1_message_bus_sender.html", null ],
    [ "MessageBusUi", "structoscr_1_1_message_bus_ui.html", null ],
    [ "MessageBusUi< Info >", "structoscr_1_1_message_bus_ui_3_01_info_01_4.html", null ],
    [ "MessageBusWrapperFromUi", "structoscr_1_1_message_bus_wrapper_from_ui.html", null ],
    [ "MessageBusWrapperFromUi< Info >", "structoscr_1_1_message_bus_wrapper_from_ui_3_01_info_01_4.html", null ],
    [ "MessageBusWrapperToUi", "structoscr_1_1_message_bus_wrapper_to_ui.html", null ],
    [ "MessageBusWrapperToUi< Info >", "structoscr_1_1_message_bus_wrapper_to_ui_3_01_info_01_4.html", null ],
    [ "MidiFileOctaver", "structoscr_1_1_midi_file_octaver.html", null ],
    [ "multichannel_audio", "structoscr_1_1multichannel__audio.html", null ],
    [ "multichannel_audio_view", "structoscr_1_1multichannel__audio__view.html", null ],
    [ "NodeItem", "structoscr_1_1_node_item.html", null ],
    [ "NormalizerFromMapper", "structoscr_1_1_normalizer_from_mapper.html", null ],
    [ "OutletInitFunc", "structoscr_1_1_outlet_init_func.html", null ],
    [ "pmf_member_type", "structoscr_1_1pmf__member__type.html", null ],
    [ "pmf_member_type< V T::* >", "structoscr_1_1pmf__member__type_3_01_v_01_t_1_1_5_01_4.html", null ],
    [ "Port", "structoscr_1_1_port.html", null ],
    [ "ProcessFactory", "structoscr_1_1_process_factory.html", null ],
    [ "ProcessModel", "classoscr_1_1_process_model.html", null ],
    [ "Protocol", "classoscr_1_1_protocol.html", null ],
    [ "ProtocolFactory", "classoscr_1_1_protocol_factory.html", null ],
    [ "ProtocolSettingsWidget", "classoscr_1_1_protocol_settings_widget.html", null ],
    [ "QPainterAdapter", "structoscr_1_1_q_painter_adapter.html", null ],
    [ "rgba_color", "structoscr_1_1rgba__color.html", null ],
    [ "RootItem", "structoscr_1_1_root_item.html", null ],
    [ "ScoreLayerFactory", "classoscr_1_1_score_layer_factory.html", null ],
    [ "Serializer", "structoscr_1_1_serializer.html", null ],
    [ "setup_control_for_exec", "structoscr_1_1setup__control__for__exec.html", null ],
    [ "setup_control_for_exec< Node, Field, N, NField >", "structoscr_1_1setup__control__for__exec_3_01_node_00_01_field_00_01_n_00_01_n_field_01_4.html", null ],
    [ "setup_control_for_exec_base", "structoscr_1_1setup__control__for__exec__base.html", null ],
    [ "update_control_in_value_in_ui", "structoscr_1_1update__control__in__value__in__ui.html", null ],
    [ "update_control_out_value_in_ui", "structoscr_1_1update__control__out__value__in__ui.html", null ],
    [ "update_control_value_in_ui", "structoscr_1_1update__control__value__in__ui.html", null ],
    [ "View", "structoscr_1_1_view.html", null ],
    [ "recursive_container_layout", "conceptoscr_1_1recursive__container__layout.html", null ],
    [ "GpuNode", "conceptoscr_1_1_gpu_node.html", null ],
    [ "GpuGraphicsNode2", "conceptoscr_1_1_gpu_graphics_node2.html", null ],
    [ "GpuComputeNode2", "conceptoscr_1_1_gpu_compute_node2.html", null ],
    [ "is_gpu", "conceptoscr_1_1is__gpu.html", null ],
    [ "has_ossia_layer", "conceptoscr_1_1has__ossia__layer.html", null ]
];