var searchData=
[
  ['macro_0',['Macro',['../class_scenario_1_1_command_1_1_macro.html',1,'Scenario::Command']]],
  ['magneticinfo_1',['MagneticInfo',['../struct_process_1_1_magnetic_info.html',1,'Process']]],
  ['magneticstates_2',['MagneticStates',['../struct_scenario_1_1_magnetic_states.html',1,'Scenario']]],
  ['magnetismadjuster_3',['MagnetismAdjuster',['../class_process_1_1_magnetism_adjuster.html',1,'Process']]],
  ['mainthreadstate_4',['MainThreadState',['../structmtk_1_1_m_i_d_i_sync_out_1_1_main_thread_state.html',1,'mtk::MIDISyncOut']]],
  ['make_5fdataspace_5',['make_dataspace',['../struct_explorer_1_1make__dataspace.html',1,'Explorer']]],
  ['make_5funit_6',['make_unit',['../struct_explorer_1_1make__unit.html',1,'Explorer']]],
  ['mappingcomponent_7',['MappingComponent',['../class_local_tree_1_1_mapping_component.html',1,'LocalTree']]],
  ['mappinginspectorfactory_8',['MappingInspectorFactory',['../class_mapping_1_1_mapping_inspector_factory.html',1,'Mapping']]],
  ['mapserializer_9',['MapSerializer',['../struct_map_serializer.html',1,'']]],
  ['marginless_10',['MarginLess',['../classscore_1_1_margin_less.html',1,'score']]],
  ['marginless_3c_20qformlayout_20_3e_11',['MarginLess&lt; QFormLayout &gt;',['../classscore_1_1_margin_less.html',1,'score']]],
  ['marginless_3c_20qgridlayout_20_3e_12',['MarginLess&lt; QGridLayout &gt;',['../classscore_1_1_margin_less.html',1,'score']]],
  ['marginless_3c_20qhboxlayout_20_3e_13',['MarginLess&lt; QHBoxLayout &gt;',['../classscore_1_1_margin_less.html',1,'score']]],
  ['marginless_3c_20qvboxlayout_20_3e_14',['MarginLess&lt; QVBoxLayout &gt;',['../classscore_1_1_margin_less.html',1,'score']]],
  ['matchedcurvetransition_15',['MatchedCurveTransition',['../class_curve_1_1_matched_curve_transition.html',1,'Curve']]],
  ['matchedcurvetransition_3c_20curveevent_3c_20element_5ft_2c_20modifier_5ft_20_3e_20_3e_16',['MatchedCurveTransition&lt; CurveEvent&lt; Element_T, Modifier_T &gt; &gt;',['../class_curve_1_1_matched_curve_transition.html',1,'Curve']]],
  ['matchedport_17',['MatchedPort',['../struct_l_v2_1_1lv2__node_1_1_matched_port.html',1,'LV2::lv2_node']]],
  ['matchedtransition_18',['matchedtransition',['../class_scenario_1_1_matched_transition.html',1,'Scenario::MatchedTransition&lt; Scenario_T, Event_T &gt;'],['../classscore_1_1_matched_transition.html',1,'score::MatchedTransition&lt; Event &gt;']]],
  ['matchedtransition_3c_20clickonevent_5fevent_20_3e_19',['MatchedTransition&lt; ClickOnEvent_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20clickoninterval_5fevent_20_3e_20',['MatchedTransition&lt; ClickOnInterval_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20clickonleftbrace_5fevent_20_3e_21',['MatchedTransition&lt; ClickOnLeftBrace_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20clickonnothing_5fevent_20_3e_22',['MatchedTransition&lt; ClickOnNothing_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20clickonrightbrace_5fevent_20_3e_23',['MatchedTransition&lt; ClickOnRightBrace_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20clickonslothandle_5fevent_20_3e_24',['MatchedTransition&lt; ClickOnSlotHandle_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20clickonstate_5fevent_20_3e_25',['MatchedTransition&lt; ClickOnState_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20clickontimesync_5fevent_20_3e_26',['MatchedTransition&lt; ClickOnTimeSync_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20event_5ft_20_3e_27',['MatchedTransition&lt; Event_T &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20moveonevent_5fevent_20_3e_28',['MatchedTransition&lt; MoveOnEvent_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20moveoninterval_5fevent_20_3e_29',['MatchedTransition&lt; MoveOnInterval_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20moveonnothing_5fevent_20_3e_30',['MatchedTransition&lt; MoveOnNothing_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20moveonslothandle_5fevent_20_3e_31',['MatchedTransition&lt; MoveOnSlotHandle_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20moveonstate_5fevent_20_3e_32',['MatchedTransition&lt; MoveOnState_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20moveontimesync_5fevent_20_3e_33',['MatchedTransition&lt; MoveOnTimeSync_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20releaseonevent_5fevent_20_3e_34',['MatchedTransition&lt; ReleaseOnEvent_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20releaseonnothing_5fevent_20_3e_35',['MatchedTransition&lt; ReleaseOnNothing_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20releaseonslothandle_5fevent_20_3e_36',['MatchedTransition&lt; ReleaseOnSlotHandle_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20releaseonstate_5fevent_20_3e_37',['MatchedTransition&lt; ReleaseOnState_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20releaseontimesync_5fevent_20_3e_38',['MatchedTransition&lt; ReleaseOnTimeSync_Event &gt;',['../classscore_1_1_matched_transition.html',1,'score']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20clickonevent_5fevent_20_3e_39',['MatchedTransition&lt; Scenario_T, ClickOnEvent_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20clickoninterval_5fevent_20_3e_40',['MatchedTransition&lt; Scenario_T, ClickOnInterval_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20clickonleftbrace_5fevent_20_3e_41',['MatchedTransition&lt; Scenario_T, ClickOnLeftBrace_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20clickonnothing_5fevent_20_3e_42',['MatchedTransition&lt; Scenario_T, ClickOnNothing_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20clickonrightbrace_5fevent_20_3e_43',['MatchedTransition&lt; Scenario_T, ClickOnRightBrace_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20clickonstate_5fevent_20_3e_44',['MatchedTransition&lt; Scenario_T, ClickOnState_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20clickontimesync_5fevent_20_3e_45',['MatchedTransition&lt; Scenario_T, ClickOnTimeSync_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20moveonevent_5fevent_20_3e_46',['MatchedTransition&lt; Scenario_T, MoveOnEvent_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20moveoninterval_5fevent_20_3e_47',['MatchedTransition&lt; Scenario_T, MoveOnInterval_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20moveonnothing_5fevent_20_3e_48',['MatchedTransition&lt; Scenario_T, MoveOnNothing_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20moveonstate_5fevent_20_3e_49',['MatchedTransition&lt; Scenario_T, MoveOnState_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20moveontimesync_5fevent_20_3e_50',['MatchedTransition&lt; Scenario_T, MoveOnTimeSync_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20releaseonevent_5fevent_20_3e_51',['MatchedTransition&lt; Scenario_T, ReleaseOnEvent_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20releaseonnothing_5fevent_20_3e_52',['MatchedTransition&lt; Scenario_T, ReleaseOnNothing_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20releaseonstate_5fevent_20_3e_53',['MatchedTransition&lt; Scenario_T, ReleaseOnState_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matchedtransition_3c_20scenario_5ft_2c_20releaseontimesync_5fevent_20_3e_54',['MatchedTransition&lt; Scenario_T, ReleaseOnTimeSync_Event &gt;',['../class_scenario_1_1_matched_transition.html',1,'Scenario']]],
  ['matches_55',['matches',['../structmatches.html',1,'']]],
  ['matchingfactory_56',['MatchingFactory',['../classscore_1_1_matching_factory.html',1,'score']]],
  ['matchingfactory_3c_20backgroundrendererfactory_20_3e_57',['MatchingFactory&lt; BackgroundRendererFactory &gt;',['../classscore_1_1_matching_factory.html',1,'score']]],
  ['matchingfactory_3c_20displayedelementsprovider_20_3e_58',['MatchingFactory&lt; DisplayedElementsProvider &gt;',['../classscore_1_1_matching_factory.html',1,'score']]],
  ['matchingfactory_3c_20displayedelementstoolpalettefactory_20_3e_59',['MatchingFactory&lt; DisplayedElementsToolPaletteFactory &gt;',['../classscore_1_1_matching_factory.html',1,'score']]],
  ['matchingfactory_3c_20inspectorwidgetfactory_20_3e_60',['MatchingFactory&lt; InspectorWidgetFactory &gt;',['../classscore_1_1_matching_factory.html',1,'score']]],
  ['matchingfactory_3c_20loadpresetcommandfactory_20_3e_61',['MatchingFactory&lt; LoadPresetCommandFactory &gt;',['../classscore_1_1_matching_factory.html',1,'score']]],
  ['matchingfactory_3c_20triggercommandfactory_20_3e_62',['MatchingFactory&lt; TriggerCommandFactory &gt;',['../classscore_1_1_matching_factory.html',1,'score']]],
  ['matchingwidget_63',['MatchingWidget',['../structoscr_1_1_matching_widget.html',1,'oscr']]],
  ['matchingwidget_3c_20field_20_3e_64',['MatchingWidget&lt; Field &gt;',['../structoscr_1_1_matching_widget_3_01_field_01_4.html',1,'oscr']]],
  ['maximum_65',['maximum',['../structavnd__tools_1_1_pattern_combiner_1_1maximum.html',1,'avnd_tools::PatternCombiner']]],
  ['maxrangespinbox_66',['MaxRangeSpinBox',['../classscore_1_1_max_range_spin_box.html',1,'score']]],
  ['maxrangespinbox_3c_20templatedspinbox_3c_20double_20_3e_20_3e_67',['MaxRangeSpinBox&lt; TemplatedSpinBox&lt; double &gt; &gt;',['../classscore_1_1_max_range_spin_box.html',1,'score']]],
  ['maxrangespinbox_3c_20templatedspinbox_3c_20float_20_3e_20_3e_68',['MaxRangeSpinBox&lt; TemplatedSpinBox&lt; float &gt; &gt;',['../classscore_1_1_max_range_spin_box.html',1,'score']]],
  ['maxrangespinbox_3c_20templatedspinbox_3c_20t_20_3e_20_3e_69',['MaxRangeSpinBox&lt; TemplatedSpinBox&lt; T &gt; &gt;',['../classscore_1_1_max_range_spin_box.html',1,'score']]],
  ['mcu_5fprotocol_70',['mcu_protocol',['../class_protocols_1_1mcu__protocol.html',1,'Protocols']]],
  ['mcudevice_71',['MCUDevice',['../class_protocols_1_1_m_c_u_device.html',1,'Protocols']]],
  ['mcuprotocolfactory_72',['MCUProtocolFactory',['../class_protocols_1_1_m_c_u_protocol_factory.html',1,'Protocols']]],
  ['mcusettingswidget_73',['MCUSettingsWidget',['../class_protocols_1_1_m_c_u_settings_widget.html',1,'Protocols']]],
  ['mcuspecificsettings_74',['MCUSpecificSettings',['../struct_protocols_1_1_m_c_u_specific_settings.html',1,'Protocols']]],
  ['melspectrum_75',['MelSpectrum',['../struct_analysis_1_1_mel_spectrum.html',1,'Analysis']]],
  ['memberspec_76',['memberspec',['../struct_gfx_1_1_shader_source_1_1_member_spec.html',1,'Gfx::ShaderSource::MemberSpec'],['../struct_j_s_1_1_qml_source_1_1_member_spec.html',1,'JS::QmlSource::MemberSpec']]],
  ['menu_77',['Menu',['../classscore_1_1_menu.html',1,'score']]],
  ['menubutton_78',['MenuButton',['../class_inspector_1_1_menu_button.html',1,'Inspector']]],
  ['menumanager_79',['MenuManager',['../classscore_1_1_menu_manager.html',1,'score']]],
  ['menus_80',['Menus',['../structscore_1_1_menus.html',1,'score']]],
  ['mergeeventmacro_81',['MergeEventMacro',['../class_scenario_1_1_command_1_1_merge_event_macro.html',1,'Scenario::Command']]],
  ['mergeevents_82',['MergeEvents',['../class_scenario_1_1_command_1_1_merge_events.html',1,'Scenario::Command']]],
  ['mergelayerinslot_83',['MergeLayerInSlot',['../class_scenario_1_1_command_1_1_merge_layer_in_slot.html',1,'Scenario::Command']]],
  ['mergercomponent_84',['MergerComponent',['../class_execution_1_1_merger_component.html',1,'Execution']]],
  ['mergeslots_85',['MergeSlots',['../class_scenario_1_1_command_1_1_merge_slots.html',1,'Scenario::Command']]],
  ['mergetimesyncs_86',['MergeTimeSyncs',['../class_scenario_1_1_command_1_1_merge_time_syncs.html',1,'Scenario::Command']]],
  ['mergetimesyncstest_87',['MergeTimeSyncsTest',['../class_merge_time_syncs_test.html',1,'']]],
  ['mergingpolicies_88',['MergingPolicies',['../struct_execution_1_1_settings_1_1_merging_policies.html',1,'Execution::Settings']]],
  ['mesh_89',['mesh',['../structscore_1_1gfx_1_1_mesh.html',1,'score::gfx::Mesh'],['../struct_threedim_1_1mesh.html',1,'Threedim::mesh']]],
  ['meshbuffers_90',['MeshBuffers',['../structscore_1_1gfx_1_1_mesh_buffers.html',1,'score::gfx']]],
  ['message_91',['message',['../struct_state_1_1_message.html',1,'State::Message'],['../struct_l_v2_1_1_message.html',1,'LV2::Message'],['../structbitfocus_1_1win32__handles_1_1message.html',1,'bitfocus::win32_handles::message'],['../structscore_1_1gfx_1_1_message.html',1,'score::gfx::Message']]],
  ['messagebusreader_92',['MessageBusReader',['../structoscr_1_1_message_bus_reader.html',1,'oscr']]],
  ['messagebussender_93',['MessageBusSender',['../structoscr_1_1_message_bus_sender.html',1,'oscr']]],
  ['messagebusui_94',['MessageBusUi',['../structoscr_1_1_message_bus_ui.html',1,'oscr']]],
  ['messagebusui_3c_20info_20_3e_95',['MessageBusUi&lt; Info &gt;',['../structoscr_1_1_message_bus_ui_3_01_info_01_4.html',1,'oscr']]],
  ['messagebuswrapperfromui_96',['MessageBusWrapperFromUi',['../structoscr_1_1_message_bus_wrapper_from_ui.html',1,'oscr']]],
  ['messagebuswrapperfromui_3c_20info_20_3e_97',['MessageBusWrapperFromUi&lt; Info &gt;',['../structoscr_1_1_message_bus_wrapper_from_ui_3_01_info_01_4.html',1,'oscr']]],
  ['messagebuswrappertoui_98',['MessageBusWrapperToUi',['../structoscr_1_1_message_bus_wrapper_to_ui.html',1,'oscr']]],
  ['messagebuswrappertoui_3c_20info_20_3e_99',['MessageBusWrapperToUi&lt; Info &gt;',['../structoscr_1_1_message_bus_wrapper_to_ui_3_01_info_01_4.html',1,'oscr']]],
  ['messagedrophandler_100',['MessageDropHandler',['../class_scenario_1_1_message_drop_handler.html',1,'Scenario']]],
  ['messageitemmodel_101',['MessageItemModel',['../class_scenario_1_1_message_item_model.html',1,'Scenario']]],
  ['messagelistproxy_102',['MessageListProxy',['../class_scenario_1_1_message_list_proxy.html',1,'Scenario']]],
  ['messagepairs_103',['MessagePairs',['../struct_scenario_1_1_command_1_1_message_pairs.html',1,'Scenario::Command']]],
  ['messagepolicy_104',['MessagePolicy',['../struct_recording_1_1_message_policy.html',1,'Recording']]],
  ['messagerecorder_105',['MessageRecorder',['../class_recording_1_1_message_recorder.html',1,'Recording']]],
  ['messagespaneldelegate_106',['MessagesPanelDelegate',['../classscore_1_1_messages_panel_delegate.html',1,'score']]],
  ['messagespaneldelegatefactory_107',['MessagesPanelDelegateFactory',['../classscore_1_1_messages_panel_delegate_factory.html',1,'score']]],
  ['messagetreeview_108',['MessageTreeView',['../class_scenario_1_1_message_tree_view.html',1,'Scenario']]],
  ['metaaction_109',['MetaAction',['../structscore_1_1_meta_action.html',1,'score']]],
  ['metacontextmenu_110',['MetaContextMenu',['../class_process_1_1_meta_context_menu.html',1,'Process']]],
  ['metadata_111',['Metadata',['../struct_metadata.html',1,'']]],
  ['metadata_3c_20category_5fk_2c_20faustdsp_3a_3afx_3c_20dsp_20_3e_20_3e_112',['Metadata&lt; Category_k, FaustDSP::Fx&lt; DSP &gt; &gt;',['../struct_metadata_3_01_category__k_00_01_faust_d_s_p_1_1_fx_3_01_d_s_p_01_4_01_4.html',1,'']]],
  ['metadata_3c_20category_5fk_2c_20oscr_3a_3aprocessmodel_3c_20info_20_3e_20_3e_113',['Metadata&lt; Category_k, oscr::ProcessModel&lt; Info &gt; &gt;',['../struct_metadata_3_01_category__k_00_01oscr_1_1_process_model_3_01_info_01_4_01_4.html',1,'']]],
  ['metadata_3c_20concretekey_5fk_2c_20faustdsp_3a_3afx_3c_20mydsp_20_3e_20_3e_114',['Metadata&lt; ConcreteKey_k, FaustDSP::Fx&lt; mydsp &gt; &gt;',['../struct_metadata_3_01_concrete_key__k_00_01_faust_d_s_p_1_1_fx_3_01mydsp_01_4_01_4.html',1,'']]],
  ['metadata_3c_20concretekey_5fk_2c_20oscr_3a_3aprocessmodel_3c_20info_20_3e_20_3e_115',['Metadata&lt; ConcreteKey_k, oscr::ProcessModel&lt; Info &gt; &gt;',['../struct_metadata_3_01_concrete_key__k_00_01oscr_1_1_process_model_3_01_info_01_4_01_4.html',1,'']]],
  ['metadata_3c_20objectkey_5fk_2c_20faustdsp_3a_3afx_3c_20mydsp_20_3e_20_3e_116',['Metadata&lt; ObjectKey_k, FaustDSP::Fx&lt; mydsp &gt; &gt;',['../struct_metadata_3_01_object_key__k_00_01_faust_d_s_p_1_1_fx_3_01mydsp_01_4_01_4.html',1,'']]],
  ['metadata_3c_20objectkey_5fk_2c_20oscr_3a_3aprocessmodel_3c_20info_20_3e_20_3e_117',['Metadata&lt; ObjectKey_k, oscr::ProcessModel&lt; Info &gt; &gt;',['../struct_metadata_3_01_object_key__k_00_01oscr_1_1_process_model_3_01_info_01_4_01_4.html',1,'']]],
  ['metadata_3c_20prettyname_5fk_2c_20faustdsp_3a_3afx_3c_20mydsp_20_3e_20_3e_118',['Metadata&lt; PrettyName_k, FaustDSP::Fx&lt; mydsp &gt; &gt;',['../struct_metadata_3_01_pretty_name__k_00_01_faust_d_s_p_1_1_fx_3_01mydsp_01_4_01_4.html',1,'']]],
  ['metadata_3c_20prettyname_5fk_2c_20oscr_3a_3aprocessmodel_3c_20info_20_3e_20_3e_119',['Metadata&lt; PrettyName_k, oscr::ProcessModel&lt; Info &gt; &gt;',['../struct_metadata_3_01_pretty_name__k_00_01oscr_1_1_process_model_3_01_info_01_4_01_4.html',1,'']]],
  ['metadata_3c_20process_3a_3adescriptor_5fk_2c_20faustdsp_3a_3afx_3c_20dsp_20_3e_20_3e_120',['Metadata&lt; Process::Descriptor_k, FaustDSP::Fx&lt; DSP &gt; &gt;',['../struct_metadata_3_01_process_1_1_descriptor__k_00_01_faust_d_s_p_1_1_fx_3_01_d_s_p_01_4_01_4.html',1,'']]],
  ['metadata_3c_20process_3a_3adescriptor_5fk_2c_20oscr_3a_3aprocessmodel_3c_20info_20_3e_20_3e_121',['Metadata&lt; Process::Descriptor_k, oscr::ProcessModel&lt; Info &gt; &gt;',['../struct_metadata_3_01_process_1_1_descriptor__k_00_01oscr_1_1_process_model_3_01_info_01_4_01_4.html',1,'']]],
  ['metadata_3c_20process_3a_3aprocessflags_5fk_2c_20faustdsp_3a_3afx_3c_20dsp_20_3e_20_3e_122',['Metadata&lt; Process::ProcessFlags_k, FaustDSP::Fx&lt; DSP &gt; &gt;',['../struct_metadata_3_01_process_1_1_process_flags__k_00_01_faust_d_s_p_1_1_fx_3_01_d_s_p_01_4_01_4.html',1,'']]],
  ['metadata_3c_20process_3a_3aprocessflags_5fk_2c_20oscr_3a_3aprocessmodel_3c_20info_20_3e_20_3e_123',['Metadata&lt; Process::ProcessFlags_k, oscr::ProcessModel&lt; Info &gt; &gt;',['../struct_metadata_3_01_process_1_1_process_flags__k_00_01oscr_1_1_process_model_3_01_info_01_4_01_4.html',1,'']]],
  ['metadata_3c_20tags_5fk_2c_20faustdsp_3a_3afx_3c_20dsp_20_3e_20_3e_124',['Metadata&lt; Tags_k, FaustDSP::Fx&lt; DSP &gt; &gt;',['../struct_metadata_3_01_tags__k_00_01_faust_d_s_p_1_1_fx_3_01_d_s_p_01_4_01_4.html',1,'']]],
  ['metadata_3c_20tags_5fk_2c_20oscr_3a_3aprocessmodel_3c_20info_20_3e_20_3e_125',['Metadata&lt; Tags_k, oscr::ProcessModel&lt; Info &gt; &gt;',['../struct_metadata_3_01_tags__k_00_01oscr_1_1_process_model_3_01_info_01_4_01_4.html',1,'']]],
  ['metadatanamepropertywrapper_126',['MetadataNamePropertyWrapper',['../class_local_tree_1_1_metadata_name_property_wrapper.html',1,'LocalTree']]],
  ['metadatawidget_127',['MetadataWidget',['../class_scenario_1_1_metadata_widget.html',1,'Scenario']]],
  ['methodprinter_128',['MethodPrinter',['../class_method_printer.html',1,'']]],
  ['metrocomponent_129',['MetroComponent',['../class_execution_1_1_metro_component.html',1,'Execution']]],
  ['metronomesounds_130',['MetronomeSounds',['../struct_execution_1_1_metronome_sounds.html',1,'Execution']]],
  ['mfcc_131',['MFCC',['../struct_analysis_1_1_m_f_c_c.html',1,'Analysis']]],
  ['midiapi_132',['MidiAPI',['../struct_protocols_1_1_settings_1_1_midi_a_p_i.html',1,'Protocols::Settings']]],
  ['mididevice_133',['MIDIDevice',['../class_protocols_1_1_m_i_d_i_device.html',1,'Protocols']]],
  ['midienumerator_134',['MidiEnumerator',['../class_protocols_1_1_midi_enumerator.html',1,'Protocols']]],
  ['midifileoctaver_135',['MidiFileOctaver',['../structoscr_1_1_midi_file_octaver.html',1,'oscr']]],
  ['midiinlet_136',['midiinlet',['../class_j_s_1_1_midi_inlet.html',1,'JS::MidiInlet'],['../class_process_1_1_midi_inlet.html',1,'Process::MidiInlet']]],
  ['midiinletfactory_137',['MidiInletFactory',['../struct_dataflow_1_1_midi_inlet_factory.html',1,'Dataflow']]],
  ['midiinputprotocolfactory_138',['MIDIInputProtocolFactory',['../class_protocols_1_1_m_i_d_i_input_protocol_factory.html',1,'Protocols']]],
  ['midiinputsettingswidget_139',['MIDIInputSettingsWidget',['../class_protocols_1_1_m_i_d_i_input_settings_widget.html',1,'Protocols']]],
  ['midikeyboardenumerator_140',['MidiKeyboardEnumerator',['../class_protocols_1_1_midi_keyboard_enumerator.html',1,'Protocols']]],
  ['midikeyboardeventfilter_141',['MidiKeyboardEventFilter',['../class_protocols_1_1_midi_keyboard_event_filter.html',1,'Protocols']]],
  ['midimessage_142',['MidiMessage',['../class_j_s_1_1_midi_message.html',1,'JS']]],
  ['midioutlet_143',['midioutlet',['../class_process_1_1_midi_outlet.html',1,'Process::MidiOutlet'],['../class_j_s_1_1_midi_outlet.html',1,'JS::MidiOutlet']]],
  ['midioutletfactory_144',['MidiOutletFactory',['../struct_dataflow_1_1_midi_outlet_factory.html',1,'Dataflow']]],
  ['midioutputprotocolfactory_145',['MIDIOutputProtocolFactory',['../class_protocols_1_1_m_i_d_i_output_protocol_factory.html',1,'Protocols']]],
  ['midioutputsettingswidget_146',['MIDIOutputSettingsWidget',['../class_protocols_1_1_m_i_d_i_output_settings_widget.html',1,'Protocols']]],
  ['midisong_147',['MidiSong',['../struct_midi_1_1_midi_track_1_1_midi_song.html',1,'Midi::MidiTrack']]],
  ['midispecificsettings_148',['MIDISpecificSettings',['../struct_protocols_1_1_m_i_d_i_specific_settings.html',1,'Protocols']]],
  ['midistyle_149',['MidiStyle',['../struct_midi_1_1_midi_style.html',1,'Midi']]],
  ['midisyncout_150',['MIDISyncOut',['../structmtk_1_1_m_i_d_i_sync_out.html',1,'mtk']]],
  ['miditrack_151',['MidiTrack',['../struct_midi_1_1_midi_track.html',1,'Midi']]],
  ['mime_152',['Mime',['../struct_mime.html',1,'']]],
  ['mimedatareader_153',['MimeDataReader',['../struct_mime_data_reader.html',1,'']]],
  ['mimedatawriter_154',['MimeDataWriter',['../struct_mime_data_writer.html',1,'']]],
  ['mimereader_155',['MimeReader',['../struct_mime_reader.html',1,'']]],
  ['mimereader_3c_20device_3a_3anodelist_20_3e_156',['MimeReader&lt; Device::NodeList &gt;',['../struct_mime_reader_3_01_device_1_1_node_list_01_4.html',1,'']]],
  ['mimereader_3c_20process_3a_3aprocessdata_20_3e_157',['MimeReader&lt; Process::ProcessData &gt;',['../struct_mime_reader_3_01_process_1_1_process_data_01_4.html',1,'']]],
  ['mimereader_3c_20state_3a_3amessagelist_20_3e_158',['MimeReader&lt; State::MessageList &gt;',['../struct_mime_reader_3_01_state_1_1_message_list_01_4.html',1,'']]],
  ['mimewriter_159',['MimeWriter',['../struct_mime_writer.html',1,'']]],
  ['mimewriter_3c_20device_3a_3afreenodelist_20_3e_160',['MimeWriter&lt; Device::FreeNodeList &gt;',['../struct_mime_writer_3_01_device_1_1_free_node_list_01_4.html',1,'']]],
  ['mimewriter_3c_20process_3a_3aprocessdata_20_3e_161',['MimeWriter&lt; Process::ProcessData &gt;',['../struct_mime_writer_3_01_process_1_1_process_data_01_4.html',1,'']]],
  ['mimewriter_3c_20state_3a_3amessagelist_20_3e_162',['MimeWriter&lt; State::MessageList &gt;',['../struct_mime_writer_3_01_state_1_1_message_list_01_4.html',1,'']]],
  ['minilayer_163',['MiniLayer',['../class_process_1_1_mini_layer.html',1,'Process']]],
  ['minimalapplication_164',['MinimalApplication',['../classscore_1_1_minimal_application.html',1,'score']]],
  ['minimalguiapplication_165',['MinimalGUIApplication',['../classscore_1_1_minimal_g_u_i_application.html',1,'score']]],
  ['minimap_166',['Minimap',['../class_scenario_1_1_minimap.html',1,'Scenario']]],
  ['minimapgraphicsview_167',['MinimapGraphicsView',['../class_scenario_1_1_minimap_graphics_view.html',1,'Scenario']]],
  ['minimum_168',['minimum',['../structavnd__tools_1_1_pattern_combiner_1_1minimum.html',1,'avnd_tools::PatternCombiner']]],
  ['miniscenarioview_169',['MiniScenarioView',['../class_scenario_1_1_mini_scenario_view.html',1,'Scenario']]],
  ['minmax_170',['minmax',['../struct_dataflow_1_1minmax.html',1,'Dataflow']]],
  ['minmaxfloatoutletfactory_171',['MinMaxFloatOutletFactory',['../struct_dataflow_1_1_min_max_float_outlet_factory.html',1,'Dataflow']]],
  ['minmaxfloatoutletitem_172',['MinMaxFloatOutletItem',['../class_dataflow_1_1_min_max_float_outlet_item.html',1,'Dataflow']]],
  ['minmaxfloatoutletminipanel_173',['MinMaxFloatOutletMiniPanel',['../class_dataflow_1_1_min_max_float_outlet_mini_panel.html',1,'Dataflow']]],
  ['minmaxheaderdelegate_174',['MinMaxHeaderDelegate',['../class_automation_1_1_min_max_header_delegate.html',1,'Automation']]],
  ['minuitdevice_175',['MinuitDevice',['../class_protocols_1_1_minuit_device.html',1,'Protocols']]],
  ['minuitprotocolfactory_176',['MinuitProtocolFactory',['../class_protocols_1_1_minuit_protocol_factory.html',1,'Protocols']]],
  ['minuitprotocolsettingswidget_177',['MinuitProtocolSettingsWidget',['../class_protocols_1_1_minuit_protocol_settings_widget.html',1,'Protocols']]],
  ['minuitspecificsettings_178',['MinuitSpecificSettings',['../struct_protocols_1_1_minuit_specific_settings.html',1,'Protocols']]],
  ['missingcommandexception_179',['MissingCommandException',['../classscore_1_1_missing_command_exception.html',1,'score']]],
  ['mixerpanel_180',['MixerPanel',['../class_mixer_1_1_mixer_panel.html',1,'Mixer']]],
  ['mmapreader_181',['MmapReader',['../struct_media_1_1_audio_file_1_1_mmap_reader.html',1,'Media::AudioFile']]],
  ['mmapview_182',['MmapView',['../struct_media_1_1_audio_file_1_1_mmap_view.html',1,'Media::AudioFile']]],
  ['mockapplication_183',['MockApplication',['../structscore_1_1testing_1_1_mock_application.html',1,'score::testing']]],
  ['modeinfo_184',['ModeInfo',['../struct_protocols_1_1_artnet_1_1_mode_info.html',1,'Protocols::Artnet']]],
  ['model_185',['model',['../class_gfx_1_1_video_1_1_model.html',1,'Gfx::Video::Model'],['../class_gfx_1_1_settings_1_1_model.html',1,'Gfx::Settings::Model'],['../class_gfx_1_1_v_s_a_1_1_model.html',1,'Gfx::VSA::Model'],['../class_library_1_1_settings_1_1_model.html',1,'Library::Settings::Model'],['../class_media_1_1_merger_1_1_model.html',1,'Media::Merger::Model'],['../class_media_1_1_metro_1_1_model.html',1,'Media::Metro::Model'],['../class_media_1_1_settings_1_1_model.html',1,'Media::Settings::Model'],['../class_media_1_1_step_1_1_model.html',1,'Media::Step::Model'],['../class_nodal_1_1_model.html',1,'Nodal::Model'],['../class_protocols_1_1_settings_1_1_model.html',1,'Protocols::Settings::Model'],['../class_remote_control_1_1_settings_1_1_model.html',1,'RemoteControl::Settings::Model'],['../class_scenario_1_1_settings_1_1_model.html',1,'Scenario::Settings::Model'],['../classvst3_1_1_model.html',1,'vst3::Model'],['../class_gfx_1_1_text_1_1_model.html',1,'Gfx::Text::Model'],['../class_gfx_1_1_render_pipeline_1_1_model.html',1,'Gfx::RenderPipeline::Model'],['../class_gfx_1_1_model_display_1_1_model.html',1,'Gfx::ModelDisplay::Model'],['../class_gfx_1_1_geometry_filter_1_1_model.html',1,'Gfx::GeometryFilter::Model'],['../class_gfx_1_1_filter_1_1_model.html',1,'Gfx::Filter::Model'],['../class_gfx_1_1_c_s_f_1_1_model.html',1,'Gfx::CSF::Model'],['../class_explorer_1_1_settings_1_1_model.html',1,'Explorer::Settings::Model'],['../class_execution_1_1_settings_1_1_model.html',1,'Execution::Settings::Model'],['../class_curve_1_1_settings_1_1_model.html',1,'Curve::Settings::Model'],['../class_curve_1_1_model.html',1,'Curve::Model'],['../class_control_surface_1_1_model.html',1,'ControlSurface::Model'],['../class_audio_1_1_settings_1_1_model.html',1,'Audio::Settings::Model']]],
  ['model_5fdisplay_5fnode_186',['model_display_node',['../class_gfx_1_1_model_display_1_1model__display__node.html',1,'Gfx::ModelDisplay']]],
  ['modelcameraubo_187',['ModelCameraUBO',['../structscore_1_1gfx_1_1_model_camera_u_b_o.html',1,'score::gfx']]],
  ['modelconsistency_188',['ModelConsistency',['../class_scenario_1_1_model_consistency.html',1,'Scenario']]],
  ['modeldisplaynode_189',['ModelDisplayNode',['../structscore_1_1gfx_1_1_model_display_node.html',1,'score::gfx']]],
  ['modelmetadata_190',['ModelMetadata',['../classscore_1_1_model_metadata.html',1,'score']]],
  ['modelprovider_191',['ModelProvider',['../class_explorer_1_1_model_provider.html',1,'Explorer']]],
  ['module_192',['Module',['../structvst_1_1_module.html',1,'vst']]],
  ['module_5fdata_193',['module_data',['../structbitfocus_1_1module__data.html',1,'bitfocus']]],
  ['module_5fhandler_194',['module_handler',['../structbitfocus_1_1module__handler.html',1,'bitfocus']]],
  ['module_5fhandler_5fbase_195',['module_handler_base',['../structbitfocus_1_1module__handler__base.html',1,'bitfocus']]],
  ['modulelibraryhandler_196',['ModuleLibraryHandler',['../class_j_s_1_1_module_library_handler.html',1,'JS']]],
  ['modvalue_197',['modvalue',['../struct_automation_1_1_recreate_on_play_1_1modvalue.html',1,'Automation::RecreateOnPlay']]],
  ['movablehandle_198',['MovableHandle',['../class_scenario_1_1_movable_handle.html',1,'Scenario']]],
  ['movebaseevent_199',['MoveBaseEvent',['../class_scenario_1_1_command_1_1_move_base_event.html',1,'Scenario::Command']]],
  ['movecommentblock_200',['MoveCommentBlock',['../class_scenario_1_1_command_1_1_move_comment_block.html',1,'Scenario::Command']]],
  ['moveevent_201',['MoveEvent',['../class_scenario_1_1_command_1_1_move_event.html',1,'Scenario::Command']]],
  ['moveevent_3c_20scenario_3a_3agoodolddisplacementpolicy_20_3e_202',['MoveEvent&lt; Scenario::GoodOldDisplacementPolicy &gt;',['../class_scenario_1_1_command_1_1_move_event.html',1,'Scenario::Command']]],
  ['moveeventclassicfactory_203',['MoveEventClassicFactory',['../class_scenario_1_1_command_1_1_move_event_classic_factory.html',1,'Scenario::Command']]],
  ['moveeventfactoryinterface_204',['MoveEventFactoryInterface',['../class_scenario_1_1_command_1_1_move_event_factory_interface.html',1,'Scenario::Command']]],
  ['moveeventinbasescenario_5fstatewrapper_205',['MoveEventInBaseScenario_StateWrapper',['../class_scenario_1_1_move_event_in_base_scenario___state_wrapper.html',1,'Scenario']]],
  ['moveeventinscenario_5fstatewrapper_206',['MoveEventInScenario_StateWrapper',['../class_scenario_1_1_move_event_in_scenario___state_wrapper.html',1,'Scenario']]],
  ['moveeventintopscenario_5fstatewrapper_207',['MoveEventInTopScenario_StateWrapper',['../class_scenario_1_1_move_event_in_top_scenario___state_wrapper.html',1,'Scenario']]],
  ['moveeventlist_208',['MoveEventList',['../class_scenario_1_1_command_1_1_move_event_list.html',1,'Scenario::Command']]],
  ['moveeventmeta_209',['MoveEventMeta',['../class_scenario_1_1_command_1_1_move_event_meta.html',1,'Scenario::Command']]],
  ['moveeventoncreationmeta_210',['MoveEventOnCreationMeta',['../class_scenario_1_1_command_1_1_move_event_on_creation_meta.html',1,'Scenario::Command']]],
  ['moveeventstate_211',['MoveEventState',['../class_scenario_1_1_move_event_state.html',1,'Scenario']]],
  ['moveeventtest_212',['MoveEventTest',['../class_move_event_test.html',1,'']]],
  ['moveinterval_213',['MoveInterval',['../class_scenario_1_1_command_1_1_move_interval.html',1,'Scenario::Command']]],
  ['moveintervalbracestate_214',['MoveIntervalBraceState',['../class_scenario_1_1_move_interval_brace_state.html',1,'Scenario']]],
  ['moveintervalinscenario_5fstatewrapper_215',['MoveIntervalInScenario_StateWrapper',['../class_scenario_1_1_move_interval_in_scenario___state_wrapper.html',1,'Scenario']]],
  ['moveintervalmacro_216',['MoveIntervalMacro',['../class_scenario_1_1_command_1_1_move_interval_macro.html',1,'Scenario::Command']]],
  ['moveintervalstate_217',['MoveIntervalState',['../class_scenario_1_1_move_interval_state.html',1,'Scenario']]],
  ['moveintervaltest_218',['MoveIntervalTest',['../class_move_interval_test.html',1,'']]],
  ['movelayerinnewslot_219',['MoveLayerInNewSlot',['../class_scenario_1_1_command_1_1_move_layer_in_new_slot.html',1,'Scenario::Command']]],
  ['moveleftbraceinscenario_5fstatewrapper_220',['MoveLeftBraceInScenario_StateWrapper',['../class_scenario_1_1_move_left_brace_in_scenario___state_wrapper.html',1,'Scenario']]],
  ['movenewevent_221',['MoveNewEvent',['../class_scenario_1_1_command_1_1_move_new_event.html',1,'Scenario::Command']]],
  ['movenewstate_222',['MoveNewState',['../class_scenario_1_1_command_1_1_move_new_state.html',1,'Scenario::Command']]],
  ['movenodes_223',['MoveNodes',['../class_process_1_1_move_nodes.html',1,'Process']]],
  ['movenodesmacro_224',['MoveNodesMacro',['../class_process_1_1_move_nodes_macro.html',1,'Process']]],
  ['movenotes_225',['MoveNotes',['../class_midi_1_1_move_notes.html',1,'Midi']]],
  ['moveonanything_5fslottransition_226',['MoveOnAnything_SlotTransition',['../class_scenario_1_1_move_on_anything___slot_transition.html',1,'Scenario']]],
  ['moveonanything_5ftransition_227',['moveonanything_transition',['../class_scenario_1_1_move_on_anything___transition.html',1,'Scenario::MoveOnAnything_Transition&lt; Scenario_T &gt;'],['../class_curve_1_1_move_on_anything___transition.html',1,'Curve::MoveOnAnything_Transition']]],
  ['moveonanythingbutevent_5ftransition_228',['MoveOnAnythingButEvent_Transition',['../class_scenario_1_1_move_on_anything_but_event___transition.html',1,'Scenario']]],
  ['moveonanythingbutponctual_5ftransition_229',['MoveOnAnythingButPonctual_Transition',['../class_scenario_1_1_move_on_anything_but_ponctual___transition.html',1,'Scenario']]],
  ['moveonanythingbuttimesync_5ftransition_230',['MoveOnAnythingButTimeSync_Transition',['../class_scenario_1_1_move_on_anything_but_time_sync___transition.html',1,'Scenario']]],
  ['moveonslothandle_5fevent_231',['MoveOnSlotHandle_Event',['../struct_scenario_1_1_move_on_slot_handle___event.html',1,'Scenario']]],
  ['moveonslothandle_5ftransition_232',['MoveOnSlotHandle_Transition',['../class_scenario_1_1_move_on_slot_handle___transition.html',1,'Scenario']]],
  ['movepoint_233',['MovePoint',['../class_curve_1_1_move_point.html',1,'Curve']]],
  ['movepointcommandobject_234',['MovePointCommandObject',['../class_curve_1_1_move_point_command_object.html',1,'Curve']]],
  ['moveprocess_235',['MoveProcess',['../class_scenario_1_1_command_1_1_move_process.html',1,'Scenario::Command']]],
  ['moverightbraceinscenario_5fstatewrapper_236',['MoveRightBraceInScenario_StateWrapper',['../class_scenario_1_1_move_right_brace_in_scenario___state_wrapper.html',1,'Scenario']]],
  ['movesegmentcommandobject_237',['MoveSegmentCommandObject',['../class_curve_1_1_move_segment_command_object.html',1,'Curve']]],
  ['movestatemacro_238',['MoveStateMacro',['../class_scenario_1_1_command_1_1_move_state_macro.html',1,'Scenario::Command']]],
  ['movetimesyncinbasescenario_5fstatewrapper_239',['MoveTimeSyncInBaseScenario_StateWrapper',['../class_scenario_1_1_move_time_sync_in_base_scenario___state_wrapper.html',1,'Scenario']]],
  ['movetimesyncinscenario_5fstatewrapper_240',['MoveTimeSyncInScenario_StateWrapper',['../class_scenario_1_1_move_time_sync_in_scenario___state_wrapper.html',1,'Scenario']]],
  ['movetimesyncintopscenario_5fstatewrapper_241',['MoveTimeSyncInTopScenario_StateWrapper',['../class_scenario_1_1_move_time_sync_in_top_scenario___state_wrapper.html',1,'Scenario']]],
  ['movetimesyncstate_242',['MoveTimeSyncState',['../class_scenario_1_1_move_time_sync_state.html',1,'Scenario']]],
  ['movetopeventmeta_243',['MoveTopEventMeta',['../class_scenario_1_1_command_1_1_move_top_event_meta.html',1,'Scenario::Command']]],
  ['mqttdevice_244',['MQTTDevice',['../class_protocols_1_1_m_q_t_t_device.html',1,'Protocols']]],
  ['mqttprotocolfactory_245',['MQTTProtocolFactory',['../class_protocols_1_1_m_q_t_t_protocol_factory.html',1,'Protocols']]],
  ['mqttprotocolsettingswidget_246',['MQTTProtocolSettingsWidget',['../class_protocols_1_1_m_q_t_t_protocol_settings_widget.html',1,'Protocols']]],
  ['mqttspecificsettings_247',['MQTTSpecificSettings',['../struct_protocols_1_1_m_q_t_t_specific_settings.html',1,'Protocols']]],
  ['mqtttcpenumerator_248',['MQTTTCPEnumerator',['../class_protocols_1_1_m_q_t_t_t_c_p_enumerator.html',1,'Protocols']]],
  ['mqtttransportwidget_249',['MQTTTransportWidget',['../class_protocols_1_1_m_q_t_t_transport_widget.html',1,'Protocols']]],
  ['multichannel_5faudio_250',['multichannel_audio',['../structoscr_1_1multichannel__audio.html',1,'oscr']]],
  ['multichannel_5faudio_5fview_251',['multichannel_audio_view',['../structoscr_1_1multichannel__audio__view.html',1,'oscr']]],
  ['multiongoingcommanddispatcher_252',['MultiOngoingCommandDispatcher',['../class_multi_ongoing_command_dispatcher.html',1,'']]],
  ['multiscriptdialog_253',['MultiScriptDialog',['../class_process_1_1_multi_script_dialog.html',1,'Process']]],
  ['multislider_254',['multislider',['../struct_j_s_1_1_multi_slider.html',1,'JS::MultiSlider'],['../struct_process_1_1_multi_slider.html',1,'Process::MultiSlider'],['../struct_widget_factory_1_1_multi_slider.html',1,'WidgetFactory::MultiSlider']]],
  ['multisliderxy_255',['multisliderxy',['../struct_process_1_1_multi_slider_x_y.html',1,'Process::MultiSliderXY'],['../struct_widget_factory_1_1_multi_slider_x_y.html',1,'WidgetFactory::MultiSliderXY']]],
  ['musicalgrid_256',['MusicalGrid',['../class_scenario_1_1_musical_grid.html',1,'Scenario']]],
  ['musicalruler_257',['MusicalRuler',['../class_scenario_1_1_musical_ruler.html',1,'Scenario']]],
  ['muxerinfo_258',['MuxerInfo',['../struct_gfx_1_1_muxer_info.html',1,'Gfx']]]
];
